#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


class VerifyValidationReportTransitionLedgerTests(unittest.TestCase):
    def test_matching_transition_ledger_passes_with_flow_flag(self) -> None:
        temp_dir = Path(tempfile.mkdtemp())
        try:
            jack_dir = temp_dir / "jack"
            jack_dir.mkdir()
            current_task = "current task"

            artifacts = {
                "repo-stack-profile.json": {"task": current_task},
                "repo-docs-lookup-plan.json": {"task": current_task},
                "repo-task-brief.json": {"task": current_task},
                "repo-task-plan.json": {
                    "task": current_task,
                    "recommended_first_edit_area": "scripts/repo_task_plan.py",
                },
                "repo-task-inspect.json": {
                    "task": current_task,
                    "recommended_first_code_edit_area": "scripts/repo_task_plan.py",
                },
                "repo-task-edit-sketch.json": {
                    "task": current_task,
                    "target_file": "scripts/repo_task_plan.py",
                },
                "repo-task-change-outline.json": {
                    "task": current_task,
                    "target_file": "scripts/repo_task_plan.py",
                },
            }
            for name, payload in artifacts.items():
                (jack_dir / name).write_text(json.dumps(payload), encoding="utf-8")

            report: dict[str, object] = {
                "task": current_task,
                "validated": [
                    "profile_repo_stack.py",
                    "profile_to_docs_lookup.py",
                    "repo_task_research.py",
                    "repo_task_plan.py",
                    "repo_task_inspect.py",
                    "repo_task_edit_sketch.py",
                    "repo_task_change_outline.py",
                ],
                "methods": [
                    f"ran: {sys.executable} scripts/run_repo_task_flow.py --repo-root {temp_dir} --task \"{current_task}\""
                ],
                "evidence_links": [
                    "jack/repo-task-plan.json",
                    "jack/repo-task-inspect.json",
                    "jack/repo-task-edit-sketch.json",
                    "jack/repo-task-change-outline.json",
                ],
                "not_validated": [],
                "assumptions": [
                    ".github/skills/doublecheck/SKILL.md present",
                    "validation_report generated by run_repo_task_flow.py (conservative, not a replacement for human review)",
                ],
                "verifier_version": "doublecheck v1",
            }
            (jack_dir / "repo-task-validation-report.json").write_text(
                json.dumps(report),
                encoding="utf-8",
            )

            ledger: dict[str, object] = {
                "task": current_task,
                "started_at": "2024-01-01T00:00:00+00:00",
                "finished_at": "2024-01-01T00:05:00+00:00",
                "stages": [
                    {
                        "stage_name": "profile_repo_stack.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-stack-profile.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "profile_to_docs_lookup.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-docs-lookup-plan.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "repo_task_research.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-task-brief.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "repo_task_plan.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-task-plan.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "repo_task_inspect.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-task-inspect.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "repo_task_edit_sketch.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-task-edit-sketch.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "repo_task_change_outline.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-task-change-outline.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "repo_task_patch_sketch.py",
                        "status": "skipped",
                        "artifact_paths": [],
                        "reason": "optional stage script not present",
                    },
                ],
                "optional_stages_encountered": [],
                "final_status": "completed",
            }
            (jack_dir / "repo-task-transition-ledger.json").write_text(
                json.dumps(ledger),
                encoding="utf-8",
            )

            env = os.environ.copy()
            env["JACK_REQUIRE_TRANSITION_LEDGER"] = "1"
            result = subprocess.run(
                [sys.executable, str(Path(__file__).with_name("verify_validation_report.py"))],
                cwd=temp_dir,
                capture_output=True,
                text=True,
                env=env,
            )

            self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
            self.assertIn("OK: transition ledger present and consistent", result.stdout)
        finally:
            shutil.rmtree(temp_dir)


if __name__ == "__main__":
    raise SystemExit(unittest.main())
