import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from datetime import datetime, timezone


class TestAdversarialReviewVerifier(unittest.TestCase):
    def test_adversarial_review_verifier_passes(self):
        with tempfile.TemporaryDirectory() as td:
            repo_root = Path(td)
            jack = repo_root / "jack"
            jack.mkdir(parents=True)

            task = "test-task"
            now = datetime.now(timezone.utc).isoformat()

            # Create required artifact files (stubs) and minimal required fields
            (jack / "repo-stack-profile.json").write_text(
                json.dumps({"task": task}), encoding="utf-8"
            )
            (jack / "repo-docs-lookup-plan.json").write_text(
                json.dumps({}), encoding="utf-8"
            )
            (jack / "repo-docs-evidence.jsonl").write_text("", encoding="utf-8")
            (jack / "repo-task-brief.json").write_text(
                json.dumps({"task": task}), encoding="utf-8"
            )
            (jack / "repo-task-plan.json").write_text(
                json.dumps({"task": task, "recommended_first_edit_area": "area"}),
                encoding="utf-8",
            )
            (jack / "repo-task-inspect.json").write_text(
                json.dumps({"task": task, "recommended_first_code_edit_area": "area"}),
                encoding="utf-8",
            )
            (jack / "repo-task-edit-sketch.json").write_text(
                json.dumps({"task": task, "target_file": "foo.py"}), encoding="utf-8"
            )
            (jack / "repo-task-change-outline.json").write_text(
                json.dumps({"task": task, "target_file": "foo.py"}), encoding="utf-8"
            )

            # Transition ledger
            stages = []
            required_stage_names = [
                "profile_repo_stack.py",
                "profile_to_docs_lookup.py",
                "repo_task_research.py",
                "repo_task_plan.py",
                "repo_task_inspect.py",
                "repo_task_edit_sketch.py",
                "repo_task_change_outline.py",
            ]
            artifact_paths = [
                "jack/repo-stack-profile.json",
                "jack/repo-docs-lookup-plan.json",
                "jack/repo-task-brief.json",
                "jack/repo-task-plan.json",
                "jack/repo-task-inspect.json",
                "jack/repo-task-edit-sketch.json",
                "jack/repo-task-change-outline.json",
            ]
            for name, path in zip(required_stage_names, artifact_paths):
                stages.append(
                    {
                        "stage_name": name,
                        "status": "completed",
                        "artifact_paths": [path],
                        "reason": "test-run",
                    }
                )

            ledger = {
                "task": task,
                "started_at": now,
                "finished_at": now,
                "stages": stages
                + [
                    {
                        "stage_name": "repo_task_patch_sketch.py",
                        "status": "skipped",
                        "artifact_paths": [],
                        "reason": "optional stage script not present",
                    }
                ],
                "optional_stages_encountered": [],
                "final_status": "completed",
            }
            (jack / "repo-task-transition-ledger.json").write_text(
                json.dumps(ledger, indent=2), encoding="utf-8"
            )

            # Validation report
            validation_report = {
                "generated_at": now,
                "task": task,
                "validated": required_stage_names,
                "methods": [
                    f'ran: {sys.executable} scripts/run_repo_task_flow.py --repo-root {repo_root} --task "{task}"'
                ],
                "not_validated": [],
                "evidence_links": [
                    "jack/repo-task-plan.json",
                    "jack/repo-task-inspect.json",
                    "jack/repo-task-edit-sketch.json",
                    "jack/repo-task-change-outline.json",
                ],
                "assumptions": [
                    ".github/skills/doublecheck/SKILL.md present",
                    "validation_report generated by run_repo_task_flow.py (conservative, not a replacement for human review)",
                ],
                "verifier_version": "doublecheck v1",
            }
            (jack / "repo-task-validation-report.json").write_text(
                json.dumps(validation_report, indent=2), encoding="utf-8"
            )

            # Artifact family manifest (include adversarial entry)
            entries = []
            for stage_name, artifact_path in zip(required_stage_names, artifact_paths):
                entries.append(
                    {
                        "stage_name": stage_name,
                        "artifact_role": f"{stage_name}_primary",
                        "artifact_path": artifact_path,
                        "required_or_optional": "required",
                        "producer": f"scripts/{stage_name}",
                        "consumers": ["human review"],
                        "output_type": "json",
                        "expected_in_current_live_flow": True,
                    }
                )

            # Add adversarial review entry
            entries.append(
                {
                    "stage_name": "post_validation",
                    "artifact_role": "adversarial_review",
                    "artifact_path": "jack/repo-task-adversarial-review.json",
                    "required_or_optional": "optional",
                    "producer": "scripts/run_repo_task_flow.py",
                    "consumers": ["human review"],
                    "output_type": "json",
                    "expected_in_current_live_flow": True,
                }
            )

            manifest = {
                "task": task,
                "generated_at": now,
                "transition_ledger_ref": "jack/repo-task-transition-ledger.json",
                "validation_report_ref": "jack/repo-task-validation-report.json",
                "artifact_family_entries": entries,
            }
            (jack / "repo-task-artifact-family-manifest.json").write_text(
                json.dumps(manifest, indent=2), encoding="utf-8"
            )

            # Adversarial review artifact
            adversarial = {
                "generated_at": now,
                "task": task,
                "review_scope": "post_validation",
                "evidence_inputs": [
                    "jack/repo-task-validation-report.json",
                    "jack/repo-task-transition-ledger.json",
                ],
                "findings": [],
                "acceptance_recommendation": "accept",
                "confidence": 0.9,
                "rationale": "Automated placeholder review for test",
                "unresolved_gaps": [],
                "recommended_return_stage": "none",
            }
            (jack / "repo-task-adversarial-review.json").write_text(
                json.dumps(adversarial, indent=2), encoding="utf-8"
            )

            # Run verifier with adversarial gate enabled
            verifier_script = (
                Path(__file__).resolve().parent / "verify_validation_report.py"
            )
            env = os.environ.copy()
            env["JACK_REQUIRE_TRANSITION_LEDGER"] = "1"
            env["JACK_REQUIRE_ARTIFACT_FAMILY_MANIFEST"] = "1"
            env["JACK_REQUIRE_ADVERSARIAL_REVIEW"] = "1"

            result = subprocess.run(
                [sys.executable, str(verifier_script)],
                cwd=str(repo_root),
                env=env,
                capture_output=True,
                text=True,
            )
            print(result.stdout)
            print(result.stderr, file=sys.stderr)
            self.assertEqual(
                result.returncode, 0, msg=f"Verifier failed: {result.stderr}"
            )


if __name__ == "__main__":
    unittest.main()
