#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


class VerifyValidationReportArtifactFamilyManifestTests(unittest.TestCase):
    def test_matching_artifact_family_manifest_passes_with_flow_flags(self) -> None:
        temp_dir = Path(tempfile.mkdtemp())
        try:
            jack_dir = temp_dir / "jack"
            jack_dir.mkdir()
            current_task = "current task"

            artifacts = {
                "repo-stack-profile.json": {"task": current_task},
                "repo-docs-lookup-plan.json": {"task": current_task},
                "repo-task-brief.json": {"task": current_task},
                "repo-task-plan.json": {
                    "task": current_task,
                    "recommended_first_edit_area": "scripts/repo_task_plan.py",
                },
                "repo-task-inspect.json": {
                    "task": current_task,
                    "recommended_first_code_edit_area": "scripts/repo_task_plan.py",
                },
                "repo-task-edit-sketch.json": {
                    "task": current_task,
                    "target_file": "scripts/repo_task_plan.py",
                },
                "repo-task-change-outline.json": {
                    "task": current_task,
                    "target_file": "scripts/repo_task_plan.py",
                },
            }
            for name, payload in artifacts.items():
                (jack_dir / name).write_text(json.dumps(payload), encoding="utf-8")

            (jack_dir / "repo-docs-evidence.jsonl").write_text(
                json.dumps({"task": current_task, "source": "docs_lookup"}) + "\n",
                encoding="utf-8",
            )

            report: dict[str, object] = {
                "task": current_task,
                "validated": [
                    "profile_repo_stack.py",
                    "profile_to_docs_lookup.py",
                    "repo_task_research.py",
                    "repo_task_plan.py",
                    "repo_task_inspect.py",
                    "repo_task_edit_sketch.py",
                    "repo_task_change_outline.py",
                ],
                "methods": [
                    f"ran: {sys.executable} scripts/run_repo_task_flow.py --repo-root {temp_dir} --task \"{current_task}\""
                ],
                "evidence_links": [
                    "jack/repo-task-plan.json",
                    "jack/repo-task-inspect.json",
                    "jack/repo-task-edit-sketch.json",
                    "jack/repo-task-change-outline.json",
                ],
                "not_validated": [],
                "assumptions": [
                    ".github/skills/doublecheck/SKILL.md present",
                    "validation_report generated by run_repo_task_flow.py (conservative, not a replacement for human review)",
                ],
                "verifier_version": "doublecheck v1",
            }
            (jack_dir / "repo-task-validation-report.json").write_text(
                json.dumps(report),
                encoding="utf-8",
            )

            ledger: dict[str, object] = {
                "task": current_task,
                "started_at": "2024-01-01T00:00:00+00:00",
                "finished_at": "2024-01-01T00:05:00+00:00",
                "stages": [
                    {
                        "stage_name": "profile_repo_stack.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-stack-profile.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "profile_to_docs_lookup.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-docs-lookup-plan.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "repo_task_research.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-task-brief.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "repo_task_plan.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-task-plan.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "repo_task_inspect.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-task-inspect.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "repo_task_edit_sketch.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-task-edit-sketch.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "repo_task_change_outline.py",
                        "status": "completed",
                        "artifact_paths": ["jack/repo-task-change-outline.json"],
                        "reason": "required stage completed",
                    },
                    {
                        "stage_name": "repo_task_patch_sketch.py",
                        "status": "skipped",
                        "artifact_paths": [],
                        "reason": "optional stage script not present",
                    },
                ],
                "optional_stages_encountered": [],
                "final_status": "completed",
            }
            (jack_dir / "repo-task-transition-ledger.json").write_text(
                json.dumps(ledger),
                encoding="utf-8",
            )

            manifest: dict[str, object] = {
                "task": current_task,
                "generated_at": "2024-01-01T00:05:00+00:00",
                "transition_ledger_ref": "jack/repo-task-transition-ledger.json",
                "validation_report_ref": "jack/repo-task-validation-report.json",
                "artifact_family_entries": [
                    {
                        "stage_name": "profile_repo_stack.py",
                        "artifact_role": "profile_json",
                        "artifact_path": "jack/repo-stack-profile.json",
                        "required_or_optional": "required",
                        "producer": "scripts/profile_repo_stack.py",
                        "consumers": ["scripts/profile_to_docs_lookup.py", "scripts/repo_task_inspect.py"],
                        "output_type": "json",
                        "expected_in_current_live_flow": True,
                    },
                    {
                        "stage_name": "profile_to_docs_lookup.py",
                        "artifact_role": "docs_lookup_plan_json",
                        "artifact_path": "jack/repo-docs-lookup-plan.json",
                        "required_or_optional": "required",
                        "producer": "scripts/profile_to_docs_lookup.py",
                        "consumers": ["scripts/repo_task_research.py"],
                        "output_type": "json",
                        "expected_in_current_live_flow": True,
                    },
                    {
                        "stage_name": "profile_to_docs_lookup.py",
                        "artifact_role": "docs_evidence_jsonl",
                        "artifact_path": "jack/repo-docs-evidence.jsonl",
                        "required_or_optional": "required",
                        "producer": "scripts/profile_to_docs_lookup.py",
                        "consumers": ["scripts/repo_task_research.py"],
                        "output_type": "jsonl",
                        "expected_in_current_live_flow": True,
                    },
                    {
                        "stage_name": "repo_task_research.py",
                        "artifact_role": "task_brief_json",
                        "artifact_path": "jack/repo-task-brief.json",
                        "required_or_optional": "required",
                        "producer": "scripts/repo_task_research.py",
                        "consumers": ["scripts/repo_task_plan.py", "scripts/repo_task_inspect.py"],
                        "output_type": "json",
                        "expected_in_current_live_flow": True,
                    },
                    {
                        "stage_name": "repo_task_plan.py",
                        "artifact_role": "task_plan_json",
                        "artifact_path": "jack/repo-task-plan.json",
                        "required_or_optional": "required",
                        "producer": "scripts/repo_task_plan.py",
                        "consumers": ["scripts/repo_task_inspect.py", "scripts/repo_task_edit_sketch.py"],
                        "output_type": "json",
                        "expected_in_current_live_flow": True,
                    },
                    {
                        "stage_name": "repo_task_inspect.py",
                        "artifact_role": "inspect_json",
                        "artifact_path": "jack/repo-task-inspect.json",
                        "required_or_optional": "required",
                        "producer": "scripts/repo_task_inspect.py",
                        "consumers": ["scripts/repo_task_edit_sketch.py", "scripts/repo_task_change_outline.py"],
                        "output_type": "json",
                        "expected_in_current_live_flow": True,
                    },
                    {
                        "stage_name": "repo_task_edit_sketch.py",
                        "artifact_role": "edit_sketch_json",
                        "artifact_path": "jack/repo-task-edit-sketch.json",
                        "required_or_optional": "required",
                        "producer": "scripts/repo_task_edit_sketch.py",
                        "consumers": ["scripts/repo_task_change_outline.py"],
                        "output_type": "json",
                        "expected_in_current_live_flow": True,
                    },
                    {
                        "stage_name": "repo_task_change_outline.py",
                        "artifact_role": "change_outline_json",
                        "artifact_path": "jack/repo-task-change-outline.json",
                        "required_or_optional": "required",
                        "producer": "scripts/repo_task_change_outline.py",
                        "consumers": ["human review"],
                        "output_type": "json",
                        "expected_in_current_live_flow": True,
                    },
                ],
            }
            (jack_dir / "repo-task-artifact-family-manifest.json").write_text(
                json.dumps(manifest),
                encoding="utf-8",
            )

            env = os.environ.copy()
            env["JACK_REQUIRE_TRANSITION_LEDGER"] = "1"
            env["JACK_REQUIRE_ARTIFACT_FAMILY_MANIFEST"] = "1"
            result = subprocess.run(
                [sys.executable, str(Path(__file__).with_name("verify_validation_report.py"))],
                cwd=temp_dir,
                capture_output=True,
                text=True,
                env=env,
            )

            self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
            self.assertIn("OK: transition ledger present and consistent", result.stdout)
            self.assertIn("OK: artifact family manifest present and consistent", result.stdout)
        finally:
            shutil.rmtree(temp_dir)


if __name__ == "__main__":
    raise SystemExit(unittest.main())
